version: "3.3"
services:
  fibonacci:
    build: "./fibonacci"
    ports: 
      - "3001:3000"
    container_name: fibonacci
    depends_on:
      - nginx
  sorter:
    build: "./number_sorter"
    container_name: sorter
    ports: 
      - "3002:3000"
    depends_on:
      - nginx
  prime:
    build: "./prime_number"
    container_name: prime
    ports: 
      - "3003:3000"
    depends_on:
      - nginx
  web:
    build: "./web"
    container_name: web
    ports: 
      - "3000:3000"
    depends_on:
      - nginx
  nginx:
    image: "nginx"
    container_name: nginx
    ports: 
      - "7070:7070"
    volumes:
      - ./web/public:/srv/static/www
      - ./tmp/nginx/default.conf:/etc/nginx/conf.d