version: "3.3"
services:
  fibonacci:
    image: node:latest
    volumes: 
      - ./fibonacci:/src/fibonacci
    working_dir: /src/fibonacci
    command: ["npm", "run", "test"]
    expose: 
      - "3001"
    ports: 
      - "3001:3000"
    container_name: fibonacci
    depends_on:
      - nginx
    

  sorter:
    image: node:latest
    volumes: 
      - ./number_sorter:/src/sorter
    working_dir: /src/sorter
    container_name: sorter
    command: ["npm", "run", "test"]
    expose: 
      - "3002"
    ports: 
      - "3002:3000"
    depends_on:
      - nginx
    

  prime:
    image: node:latest
    volumes: 
      - ./prime_number:/src/prime
    working_dir: /src/prime
    container_name: prime
    command: ["npm", "run", "test"]
    expose: 
      - "3003"
    ports: 
      - "3003:3000"
    depends_on:
      - nginx
    

  web:
    image: node:latest
    volumes: 
      - ./web:/src/web
    working_dir: /src/web
    container_name: web
    command: ["npm", "run", "test"]
    expose: 
      - "3000"
    ports: 
      - "3000:3000"
    depends_on:
      - nginx
    

  nginx:
    image: "nginx"
    container_name: nginx
    ports: 
      - "7070:7070"
    volumes:
      - ./web/public:/srv/static/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./tmp/nginx/default.conf:/etc/nginx/conf.d
